/* Generated By:JavaCC: Do not edit this line. JSONTreeConstants.java Version 5.0 */
public interface JSONTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;
  public int JJTEXPR4 = 4;
  public int JJTEXPR5 = 5;
  public int JJTEXPR6 = 6;
  public int JJTEXPR7 = 7;
  public int JJTEXPR8 = 8;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
    "Expr4",
    "Expr5",
    "Expr6",
    "Expr7",
    "Expr8",
  };
}
/* JavaCC - OriginalChecksum=4d309e47ba86fef9c4313259d49ff5c4 (do not edit this line) */
