/* Generated By:JJTree&JavaCC: Do not edit this line. JSONConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JSONConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int STRING = 6;
  /** RegularExpression Id. */
  int OPENB = 7;
  /** RegularExpression Id. */
  int CLOSEB = 8;
  /** RegularExpression Id. */
  int OPENA = 9;
  /** RegularExpression Id. */
  int CLOSEA = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int NODES = 12;
  /** RegularExpression Id. */
  int LINKS = 13;
  /** RegularExpression Id. */
  int NAME = 14;
  /** RegularExpression Id. */
  int GROUP = 15;
  /** RegularExpression Id. */
  int SOURCE = 16;
  /** RegularExpression Id. */
  int TARGET = 17;
  /** RegularExpression Id. */
  int VALUE = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<INTEGER>",
    "<STRING>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"\\\"nodes\\\":\"",
    "\"\\\"links\\\":\"",
    "\"\\\"name\\\":\"",
    "\"\\\"group\\\":\"",
    "\"\\\"source\\\":\"",
    "\"\\\"target\\\":\"",
    "\"\\\"value\\\":\"",
  };

}
