/* Generated By:JJTree&JavaCC: Do not edit this line. JSONConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JSONConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int OPENB = 6;
  /** RegularExpression Id. */
  int CLOSEB = 7;
  /** RegularExpression Id. */
  int OPENA = 8;
  /** RegularExpression Id. */
  int CLOSEA = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int COLON = 11;
  /** RegularExpression Id. */
  int NODES = 12;
  /** RegularExpression Id. */
  int LINKS = 13;
  /** RegularExpression Id. */
  int NAME = 14;
  /** RegularExpression Id. */
  int GROUP = 15;
  /** RegularExpression Id. */
  int SOURCE = 16;
  /** RegularExpression Id. */
  int TARGET = 17;
  /** RegularExpression Id. */
  int VALUE = 18;
  /** RegularExpression Id. */
  int STRING = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<INTEGER>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "\"\\\"nodes\\\"\"",
    "\"\\\"links\\\"\"",
    "\"\\\"name\\\"\"",
    "\"\\\"group\\\"\"",
    "\"\\\"source\\\"\"",
    "\"\\\"target\\\"\"",
    "\"\\\"value\\\"\"",
    "<STRING>",
  };

}
